### ISSUE TITLE
figure out apollo router hive versioning

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/console#3314]
- [ ] Versioning Router on Github/Docker image https://github.com/graphql-hive/console/pull/5941
- [x] Version Router on crates.io for extensions https://github.com/kamilkisiela/graphql-hive/issues/291

**Comment by dotansimha** [comment]
This one is available now with versions. You can find more info here: https://the-guild.dev/graphql/hive/product-updates/2024-11-19-apollo-router-hive-versioning
