### ISSUE TITLE
Feedback for “OIDC Login”

### ISSUE THREAD

**Issue by PlayAnyData** [graphql-hive/console#6117]
Hey,

I have got a quick question regarding OIDC Login options. We are self-hosting Hive and documentation on self-hosting does not include MS Azure. However, the cloud version does include this: https://the-guild.dev/graphql/hive/docs/management/sso-oidc-provider vs: https://the-guild.dev/graphql/hive/docs/self-hosting/oidc-login Does this mean Azure SSO is not available for self-hosting or is the documentation simply lacking this fact. If the latter is true, is there anything specific we would need to take into account?

**Comment by kamilkisiela** [comment]
OIDC is the same in both. The Hive Cloud is identical to self-hosted Hive, it's the same code, same features.
It's just that one instruction has Azure and the other does not.

**Comment by PlayAnyData** [comment]
Great! Thanks for the clarification.
